apiVersion: v1
kind: ConfigMap
metadata:
  name: image-resizer-config
  namespace: k8s-basselsi
  labels:
    app: image-resizer-api
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  PORT: "8080"
  MAX_IMAGE_SIZE: "10485760"  # 10MB in bytes
